services:
  application:
    image: japneet97/express-app-cicd
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8000:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
      -  WATCHTOWER_LABEL_ENABLE=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower